### ISSUE TITLE
Combine Validate & Save, and Done Buttons

### ISSUE THREAD

**Issue by riversn** [bradmartin333/GridMaker#19]
Combine Validate & Save, and Done Buttons

No reason to have separate buttons, the X button does what 'done' should

**Comment by bradmartin333** [comment]
Looked at `Composer.cs` and they do have different functions, but they could maybe be combined into one button.

Current functions:
- X button: cancel and hide dialog, nothing changed
- Done button: sends a DialogResult.OK to the host window, but it may or may not be used in the XFER-SEYR Panel
- Validate & Save: not super pretty, but if the grid is valid, it saves it and reloads the UI... not sure if anything happens for an invalid grid? I will have to refamiliarize myself with it

I can combine some functions, but I remember liking the ability to click Validate & Save, then recheck the plot in the preview form before closing. Is the reason for this issue a speed thing? I could see an invalid grid being ignored or the user running with a different grid than they think is saved. 

A simple mockup might be necessary - meaning edit a screenshot and add some text about desired result of btn clicks

**Comment by riversn** [comment]
Validate and Save as a button is redundant for 'Done' 

If user wants to test the plot preview, the plot preview button should just run the validate and save function before opening the plot preview. 
'Done button' should validate & save, and then close. But if there's a validation error it should say/report it instead of closing. 

No need for two separate buttons.
