### ISSUE TITLE
Row/Col mixed

### ISSUE THREAD

**Issue by riversn** [bradmartin333/GridMaker#21]
![image](https://github.com/bradmartin333/GridMaker/assets/101815602/cf285577-aa39-4e8b-a721-355aaeb4b3a0)
Should be 3,2 not 2,3

**Comment by bradmartin333** [comment]
in Functions.DrawTiles(): `string location = string.Format("{0}, {1}", tileUnderCursor.Location.X + 1, tileUnderCursor.Location.Y + 1);`

in Composer: `rtb.Text += $"{(UseRC ? point.Y : point.X) + 1}, {(UseRC ? point.X : point.Y) + 1}\n";`

so, Functions needs access to UseRC to flip X and Y
