### ISSUE TITLE
Options to pull XferPrint recipe info

### ISSUE THREAD

**Issue by riversn** [bradmartin333/GridMaker#9]
Options to pull XferPrint recipe info

If I don't remember grid pitches, I want to pull target pitch info from print recipe and add that as A/B pitches.

A = Target Region pitches
B = # of stamp posts * stamp post spacing
C = keep user defined because optic difference?

**Comment by bradmartin333** [comment]
XFER-907

**Comment by riversn** [comment]
"Import grid distances from XferPrint Recipes"

Need an 'import' button under file to do this

**Comment by bradmartin333** [comment]
This is an XferPrint task, not gridmaker
